- pyproject.toml
- requirements.txt
- src/rocm_docs/__init__.py
- src/rocm_docs/data/_static/custom.css
- src/rocm_docs/data/_static/rocm_header.css
The current version of `sphinx-book-theme` does not allow for breadcrumbs. Version 1.0.0 will, but is currently in the release candidate stage.
> Switch to use sphinx-book-theme 1.0.0rc2

- src/rocm_docs/__init__.py
- src/rocm_docs/util.py
When the repository being built is private and no token is provided, we cannot connect to GitHub to get pull request information, so pull request builds will fail. This PR disables the edit button when we cannot get sufficient information to enable it, and adds some placeholder information for formatting the table of contents.
> Accomodate private repos without token

- src/rocm_docs/data/_static/custom.css
Make the cookie settings align vertically with other footer links
Remove the red hover effect
> Remove hover effect from cookie settings

- src/rocm_docs/__init__.py
Enables two MyST extensions:
- [`replacements`](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#typography) converts `(tm) (c)` to `™ ©`.
- [`fieldlist`](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#field-lists) is more visually pleasing than using tables to document command arguments.
> Add fieldlist and replacements MyST extension

- pyproject.toml
- requirements.txt
- src/rocm_docs/__init__.py
Since [CK](https://github.com/ROCmSoftwarePlatform/composable_kernel/) is the only repo that uses this extension and it requires a custom config, it doesn't seem worthwhile to add it as a dependency to all repos that use rocm-docs-core.
Successful test build using hipBLAS: https://readthedocs.com/projects/advanced-micro-devices-hipblas/builds/1373708/
> Separate bibtex requirement from rocm-docs-core

- src/rocm_docs/__init__.py
Look up doxygen in the path before trying to execute it using `shutil.which`.
Using full paths to executables [is recommended][1] anyways as it avoids differences in platform search behaviour.
[1]: https://docs.python.org/3/library/subprocess.html#subprocess.Popen
> Improve error message if doxygen not found in PATH

- docs/.gitignore
- docs/demo/doxygen/Doxyfile
- src/rocm_docs/__init__.py
- src/rocm_docs/data/_doxygen/extra_stylesheet.css
- src/rocm_docs/data/_doxygen/footer.html
- src/rocm_docs/data/_doxygen/header.html
- src/rocm_docs/data/_doxygen/stylesheet.css
Style the doxysphinx generated pages using [doxygen-awesome-css](https://github.com/jothepro/doxygen-awesome-css)
modified by integrating into the sphinx-book-theme's dark/light themes.
The doxygen header/footer and the the stylesheets are copied in with rocm-docs-core, projects need to set the path to them in their Doxyfile to use these themes.
This also removes the need for sass (and node.js) to be installed as the stylesheets are installed in their already processed form.
Stacked upon #32, it should be merged first.
> API reference styling

- src/rocm_docs/data/_static/custom.css
- src/rocm_docs/data/_static/rocm_header.css
Fonts scale to different screen sizes
Screen Width: Font Size relative to root element
less than 1000px: 0.5x 
1000px-2000px: 0.75x
greater than 2000px: 1.25x
Also, ensure the ROCm logo doesn't distort or overextend the header
> Make fonts scale to different screen sizes

- src/rocm_docs/rocm_docs_theme/static/custom.css
- src/rocm_docs/rocm_docs_theme/static/rocm_footer.css
- Lower small font-size threshold until its absolutely required for
fitting the content on screen, and make it slightly bigger in that case.
This allows to keep the normal font-size when e.g. splitting the
screen on a normal laptop.
- Remove the import of `theme.css` as custom.css is applied as an *extra*
stylesheet therefore its already part of the style.
- Change the rocm-footers height to be min-height instead, so its content
does not overflow it, when it needs to display more rows (on narrow
devices).
~~Stacked on top of #41, to avoid conflicts.~~ Merged
> Various stlysheet fixes

- .github/workflows/release.yml
- .github/workflows/sync_branches.yml
- .github/workflows/version-bump.yml
- Fix the release pipeline by using the correct variable
- allow running all of the release pipelines manually to aid debugging
- add a pipeline to ~~merge~~ fast-forward the branch it is running on into develop, can be triggered by hand. It is also run as a part of the release process.
- prevent partial pushes for the bump commit by using the `--atomic` option to `git push`
See ~~https://github.com/StreamHPC/rocm-docs-core/actions/runs/4680331546~~ https://github.com/StreamHPC/rocm-docs-core/actions/runs/4686889321 for how a complete run of this pipeline looks like (the push job is failing in the fork because it doesn't have access to pypi which is expected) .
> Auto release fixes

- src/rocm_docs/rocm_docs_theme/static/custom.css
- src/rocm_docs/rocm_docs_theme/static/rocm_footer.css
The CSS fixes were lost during the restoration of main, this is the same commit as in #46 rebased, to apply them again in develop.
> Reland css fixes

- src/rocm_docs/__init__.py
- src/rocm_docs/core.py
- #88 results in the sphinx-rtd-theme being used when built using read-the-docs, restore the customized theme by forcing in the legacy api
- change the new extension api to NOT set `html_theme` by default.
- this is the only sane option that still allows the user to override the setting, because there's no way to distinguish if it was overriden by RTD or the user  
- it is also more explicit, and makes local and RTD builds be more consistent (they will both apply a "default" theme if none is specified the sphinx default and the rtd default respectively)
- This is a breaking change for hypotethical users of the new extension interface; fortunately there are none as all current projects still use the legacy (importing `rocm_docs` and using `rocm_docs.setup()`) way of rocm-docs-core :)
> Fix theme on rtd

- src/rocm_docs/__init__.py
Fix builds using the legacy interface that do not enable doxygen.
Previously these projects failed with an 'AttributeNotFoundError' because `ROCMDocs` only set the doxygen related attributes when `run_doxygen` was called.
Set them to `None` now by default, they will get ignored if doxygen isn't enabled anyway.
This should fix https://github.com/RadeonOpenCompute/ROCm/pull/2041 (when it gets released).
> fix(legacy): fix builds without doxygen

- pyproject.toml
set commitizen's `major_version_zero` option to not advance the project to 1.0.0 upon a breaking change [1].
[1]: https://commitizen-tools.github.io/commitizen/bump/#-major-version-zero
@saadrahim, @lawruble13 if you want to do a merge to main (i.e. trigger a release) please get this in first, as I just realized this setting needed to be set, and I don't think we want to go to 1.0.0 just yet.
> ci(release): keep major version at zero

- .github/dependabot.yml
- docs/conf.py
- src/rocm_docs/__init__.py
closes #22 
Grabs VERSION_STRING from CMakeLists.txt if it has it. Also has option to pass in version argument to override.
examples:
`docs_core = ROCmDocs("ROCm Documentation")` > ROCm Documentation (no version arg or VERSION_STRING)
`docs_core = ROCmDocs("ROCm Documentation", "5.6.0 Alpha")` > ROCm Documentation 5.6.0 Alpha (using version arg)
`docs_core = ROCmDocs("hipBLAS Documentation")` > hipBLAS Documentation 1.1.0 (using VERSION_STRING)
`docs_core = ROCmDocs("hipBLAS Documentation", "2.0")` > hipBLAS Documentation 2.0 (using version arg
> Add version numbers to generated documentation

- .readthedocs.yaml
Seems like read-the-docs is updating the dependencies of rocm-docs-core when it installs it basically destroying our pinning of packages in `requirements.txt`.
With the changed order `requirements.txt` takes priority and downgrades packages that have been upgraded in the previous step, and things seem to work out.
This still leaves the issue of `doxysphinx` 3.3.0 failing, but that can be tackled later.
> ci(rtd): Try to restore pinning by changing installation order

- .wordlist.txt
Add Original equipment manufacturer or OEM to wordlist, @Naraenda is there a way to set a lower limit on word length to check? Three letter acronyms are going to get kind of frustrating otherwise I think.
> ci: add to wordlist

- .gitignore
- docs/conf.py
- src/rocm_docs/core.py
- src/rocm_docs/rocm_docs_theme/components/article-info.html
- src/rocm_docs/rocm_docs_theme/components/left-side-menu.html
- src/rocm_docs/rocm_docs_theme/sections/footer.html
@Maetveis @lawruble13 
> Example: https://advanced-micro-devices-demo--139.com.readthedocs.build/projects/rocm-docs-core/en/139/index.html
[Use default values if not specified](https://github.com/RadeonOpenCompute/rocm-docs-core/pull/139/commits/69c5b952bd3f33d1f243a542e8df6ab3e136b314):
- set default os to linux and windows
- auto set date to time the source page was last modified on git
- closes https://github.com/RadeonOpenCompute/rocm-docs-core/issues/143
- set auto read time (using 200wpm, word len 5 chars) 
- closes https://github.com/RadeonOpenCompute/rocm-docs-core/issues/142
> Article-info example

- .spellcheck.yaml
- .wordlist.txt
Markdown supports "out-of-line" links of the format [link-text][link-name], followed by [link-name]: <link-url> on its own line somewhere in the document.
Don't spellcheck link-name or the link definition line.
The word list additions are for the GPU isolation guide.
> ci(spellcheck): Ignore out of line links in spellcheck, add some new words

- src/rocm_docs/core.py
since Read the Docs uses git version 2.17.1, which does not support the `%cs` format option
> fix(core.py): use older version of pretty format in git log command

- src/rocm_docs/core.py
- src/rocm_docs/rocm_docs_theme/components/article-info.html
change from icons to text due to copyright issues with Windows logo
> Use text instead of icons for article OS info

- src/rocm_docs/core.py
To allow, for example, renaming .sphinx and .doxygen directories to sphinx and doxygen by setting `external_toc_path` and doxygen_root (when calling run_doxygen) in `conf.py`
eg:
```
external_toc_path = "./sphinx/_toc.yml"
...
docs_core.run_doxygen(doxygen_root="doxygen")
```
> Allow overriding path to external toc path

- src/rocm_docs/rocm_docs_theme/static/custom.css
- src/rocm_docs/rocm_docs_theme/static/rocm_header.css
- Fix menu having a scrollbar when it is not needed
- Fix the page "jumping" when the sidebar is opened on small screens
- Animate the header appearing with the sidebar on small screens
- Fix the read the docs version selector not appearing on the sidebar on small screens
> Another round of good 'ol css fixes

- src/rocm_docs/core.py
The current method of inserting article info can only work for the (multi-page) HTML builds, but it shouldn't cause a build failure. This is now fixed by skipping if the file does not exists.
> fix(article-info): hotfix non-html builds breaking

- src/rocm_docs/rocm_docs_theme/sections/header.html
Does this for the GitHub and Support links in the header
eg: https://github.com/ROCm-Developer-Tools/rocgdb-docs > https://github.com/ROCm-Developer-Tools/rocgdb
> fix(header.html): point docs repos to library repos

- .wordlist.txt
Fixes CI on https://github.com/RadeonOpenCompute/ROCm/pull/2167
> ci(spellcheck): adds "disambiguates" to vocabulary

- src/rocm_docs/theme.py
Add an announcement banner at the top for information on the documentation transition.
Do not merge until the announcement link is updated.
> Add announcement banner

- src/rocm_docs/doxygen.py
Removes an extra print statement and use urllib to simplify regex
RE: https://github.com/ROCmSoftwarePlatform/hipSOLVER/pull/161#pullrequestreview-1434766240
Update: Reverted change to use urlparse in latest
> `urlparse` probably won't work, as we also need to accommodate SSH remotes (e.g. `git@github.com:RadeonOpenCompute/rocm-docs-core.git`)
> Refactor utility code

- .wordlist.txt
- docs/.sphinx/_toc.yml.in
- docs/user_guide/article_info.md
- docs/user_guide/projects_yaml.md
- src/rocm_docs/rocm_docs_theme/components/left-side-menu.html
closes https://github.com/RadeonOpenCompute/rocm-docs-core/issues/191
also renames main doc link to ROCm Documentation Home
> Add User Guide Docs

- pyproject.toml
to resolve issue with dependabot
```
updater |   ERROR: Could not find a version that satisfies the requirement doxysphinx==3.2.1 (from rocm-docs-core[api_reference]==0.13.1) (from versions: 3.3.0, 3.3.1, 3.3.2, 3.3.3)
...
updater | pip._internal.exceptions.DistributionNotFound: No matching distribution found for doxysphinx==3.2.1 (from rocm-docs-core[api_reference]==0.13.1)
```
> build(pyproject.toml): set min doxysphinx version to 3.3.2 when using api_reference

- README.md
- src/rocm_docs/__init__.py
since each project has the version string in a different location, this must be done on a case-by-case basis
> fix(__init__.py): stop searching CMakeLists.txt for version string

- src/rocm_docs/data/projects.yaml
- src/rocm_docs/projects.py
- src/rocm_docs/rocm_docs_theme/components/left-side-menu.html
- src/rocm_docs/rocm_docs_theme/sections/footer.html
- src/rocm_docs/rocm_docs_theme/sections/header.html
Project urls (from `projects.yaml`) are exposed as `projects[project_name]` to jinja now, this includes the branch mapping logic.
Use this to set the main doc link, this makes versioned releases link to the correct version of the main doc page (rocm).
> feat(projects): expose project urls to html templates

- src/rocm_docs/projects.py
point directly to https://rocm.docs.amd.com/en/latest/
> fix: hardcode the url for ROCm docs

- src/rocm_docs/rocm_docs_theme/layout.html
Adds the google-site-verification metadata near the end of the `<head>` section for all pages via the `layout.html`
> Include metadata in head tag for all pages

- src/rocm_docs/theme.py
This flavor doesn't ship with any files, they are to be provided by users.
To use this flavor make a customized copy of a flavor in the project directory and set the following options in `conf.py`
```python
html_theme_options["flavor"] = "local"
templates_path = ["."] # Use the current folder for templates
```
> feat: Add "local" flavor for providing the flavor in the project

- src/rocm_docs/doxygen.py
As part of the effort to build the documentation of (potentially multiple) projects from CMake, I've added the ability for Sphinx to call a Doxygen install that isn't on the PATH (as on Windows, that is rarely the case). Specifying `-D doxygen_executable=<path_to_doxygen.exe>` then sphinx will use that instead of asking `shutil` where it's found on the PATH.
> feat: Add config option to specify doxygen exe

- src/rocm_docs/core.py
Previously it was erroneously skipped when the relevant config (`notfound_urls_prefix`) was NOT defined, we should skip when it is defined to not overwrite the users intention.
Additionally the contained logic didn't account for the sub-project layout of the urls (i.e. the url for rocm-docs-core is `/projects/rocm-docs-core/en/latest`). This resulted on 404 pages not working on branches that don't exists on the main documentation site.
> fix(core.py): fix setting up the base url for the 404 page

- src/rocm_docs/data/projects.yaml
https://github.com/RadeonOpenCompute/rocm-cmake/pull/142
> fix(projects.yaml): Add ROCmCMakeBuildTools to projects.yaml

- .github/workflows/linting.yml
- .github/workflows/pull_request.yml
- .github/workflows/version-bump.yml
Because of branch protection rules status checks are required before merging, but they are not triggered by pushes from github actions (pushes authenticated via `GITHUB_TOKEN`).
Quoting from [Github actions / Using the `GITHUB_TOKEN` in a workflow](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
> When you use the repository's `GITHUB_TOKEN` to perform tasks, events triggered by the `GITHUB_TOKEN`, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.
> ...
> For example, if a workflow run pushes code using the repository's `GITHUB_TOKEN`, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
To remedy this and …
> "Skip" status checks for version bump commit

- docs/.gitignore
- src/rocm_docs/projects.py
- src/rocm_docs/rocm_docs_theme/theme.conf
- [rocm-docs-core](https://github.com/RadeonOpenCompute/rocm-docs-core) version is bumped by this commit
- the update will be pushed to all projects
- then cherry picked into `release/rocm-rel-5.7` branch
> Update header version to 5.7

- src/rocm_docs/rocm_docs_theme/flavors/rocm/header.jinja
to prevent error with rocm-docs-core pointing to rocm-core
> Fix(header.jinja): only modify theme_repository_url if it ends with -docs

- src/rocm_docs/doxygen.py
- src/rocm_docs/util.py
For relative files this is what we want most of the time, as we're copying
sources to be picked up by sphinx. Usually the configuration and source
directory are the same, so this error went unnoticed.
Also fix/simplify creating the folder for `_doxygen`
> Copy files relative to source directory

- pyproject.toml
- requirements.txt
- src/rocm_docs/py.typed
Without this file type out definitions are not visible to projects using rocm_docs_core. This is not really a problem since our users are sphinx cofiguration files `conf.py` where type-checking doesn't provide much benefit, but its still nice to export our type annotations given that we have them.
> build: Add py.typed marker to "export" type definitions

- src/rocm_docs/doxygen.py
PR #306 introduced a config option to set doxygen executable, but we failed to propagate it to doxysphinx too. Before this change doxysphinx always looks for the command `doxygen` in the PATH.
> fix(doxygen.py): Pass doxygen executable to doxysphinx

- src/rocm_docs/theme.py
- src/rocm_docs/util.py
Handle in the theme when we're not inside a git repo, by not providing urls in that case.
For testing setting up a git repo for the execution of tests would be very painful, so lets avoid it.
> fix(theme.py): Partially handle not being in a git repository

- docs/conf.py
- docs/developer_guide/projects_yaml.md
- src/rocm_docs/projects.py
- tests/test_sites.py
Allow to fetch project sphinx indices explicitly
Description copied from the proposed documentation of the feature (projects.yaml.md):
By default the inventories of all external projects defined in `projects.yaml`
will be downloaded. This can take a long time as it requires a network request
for each external project.
The `external_projects` configuration option can be set to a list with the names
of remote projects to fetch inventories from & enable links to.
The list must be a subset of the project names defined in `projects.yaml`.
The default value of `"all"` means to fetch all projects.
References to projects that are not in `external_projects` will not be resolved.
This applies to the terms of contents too, where unresolved references will
likely cause an error.
ref: #182
Based on …
> Explicit projects

- .wordlist.txt
added missing words required by #466.
```
OMPI
Tensorboard
centos
dev
pytorch
tensorflow
tf
ubuntu
```
> added missing words required by #466.

- src/rocm_docs/util.py
Support for Community sites
Note: readthedocs.org gives domains in the form <project>.io
> fix(util.py): Modify RTD regex to allow for .org sites

- pyproject.toml
- requirements.txt
- src/rocm_docs/doxygen.py
- tests/sites/doxygen/extension/conf.py
- tests/sites/doxygen/legacy/conf.py
- tests/sites/templates/doxygen/.doxygen/A.cpp
- tests/sites/templates/doxygen/.sphinx/_toc.yml.in
- tests/sites/templates/doxygen/doxylink.md
- tests/test_doxygen.py
**If** doxylink is enabled by the project
(by adding `sphinxcontrib.doxylink` to `extensions`) and `doxygen_html` is set, then set the settings of doxylink automatically. The role name is set to "doxygen", therefore references to the doxygen documentation in the current project can be typed as 
```
{doxygen}`entity-in-doxygen-doc`
```
which could be a file, functions, namespace etc.
This is only covers references within the same project, outside references will be done later.
> feat(doxygen.py): automatic setup of doxylink

- docs/conf.py
PR #443 broke linking.md, as it contains external an external reference to the main ROCm documentation page, so external_projects must mention it.
> docs(conf.py): add rocm to external_projects in conf.py

- docs/developer_guide/projects_yaml.md
- src/rocm_docs/projects.py
- tests/test_projects.py
Resolve project urls in jinja templates `projects["project_name"]` and in the TOC (`_toc.yml.in`) regardless of the setting of `external_projects`.
The HTML templates make use of the URL of the ROCm main project, which were broken with the previous behaviour. Having it available in the TOC too is more consistent, and there is no extra cost to it, as we already have this information from `projects.yaml` without downloading the sphinx inventories.
> fix(projects): always resolve project references in TOC and templates

- .devcontainer/devcontainer.json
- .gitpod.yml
Better toml is deprecated and replaced by even better toml.
> Replace deprecated vscode extension

- src/rocm_docs/doxygen.py
If the forked version of doxysphinx is detected, then enable the extended TOC based on the doxygen tagfile.
Projects that wish to use this have to replace their doxysphinx version in `requirements.in/txt` to the fork of doxysphinx that contains the necessary changes.
I.e. they should add:
`doxysphinx @ git+https://github.com/StreamHPC/doxysphinx.git@tagfile_toc`
> feat(doxygen.py): Enable doxygen extended toc with forked doxysphinx

- docs/conf.py
- pyproject.toml
- src/rocm_docs/data/projects.yaml
- src/rocm_docs/rocm_docs_theme/flavors/rocm-api-tools-list/left-side-menu.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm-docs-home/footer.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm-docs-home/header.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm-docs-home/left-side-menu.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm/left-side-menu.jinja
- src/rocm_docs/theme.py
relates to https://github.com/RadeonOpenCompute/rocm-docs-core/issues/534 
Rename rocm-api-tools-list theme to rocm-docs-home
rocm theme left navbar points to api tools list page
rocm-docs-home left navbar points to rocm docs home page
> Swap themes

- src/rocm_docs/rocm_docs_theme/flavors/rocm/header.jinja
Also direct install doc repos to ROCm repo. Related to https://github.com/ROCm/ROCm/issues/2737#issuecomment-1876818280
> fix(header.jinja): Fix support link in header for rocm-docs-core

- src/rocm_docs/rocm_docs_theme/flavors/rocm-blogs/left-side-menu.jinja
https://github.com/ROCm/rocm-docs-core/issues/635
> fix(left-side-menu.jinja): Set main doc link for blogs flavor

- src/rocm_docs/rocm_docs_theme/theme.conf
Release version of rocm-docs-core with no banner and 6.0.2 and also includes additional fixes from v0.35.1
> fix(theme.conf): Create point fix for 6.0.2

- src/rocm_docs/rocm_docs_theme/layout.html
For Google Search Console
Metadata content was changed during updates
RE: ROCm Users: As of March 15, 2024, [docs.amd.com](http://docs.xilinx.com/) no longer redirects to [rocm.docs.amd.com](http://rocm.docs.amd.com/). ROCm documentation can be directly referenced at [rocm.docs.amd.com](http://rocm.docs.amd.com/).
> fix(layout.html): Update google-site-verification metadata

- pyproject.toml
build(pyproject.toml): Remove major_version_zero = true (default is false) for version 1.x.x
--major-version-zero is meaningless for current version 1.0.0
> Remove major_version_zero = true from pyproject.toml

- src/rocm_docs/rocm_docs_theme/404.html
Remove relative link in 404.html page
Navigation is no longer flat, so relative links will fail for some pages
> fix(404.html): Remove relative link in 404.html page

- src/rocm_docs/rocm_docs_theme/static/custom.css
This PR adds `margin-bottom: 1rem;` in custom.css to give images in rST files the same spacing as those in Markdown.
The issue is because:
1. Images generated from Markdown files are rendered as `<p><img /></p>`
2. rocm-docs Sphinx theme adds 1rem margin-bottom to \<p> tags by default.
3. Images from rST files are rendered as `<img />`.
Example of rST image before css update: https://rocm.docs.amd.com/en/latest/what-is-rocm.html
This fix should apply across all ROCm docs.
> fix(custom.css): add bottom margin to images in rst files

- src/rocm_docs/data/projects.yaml
For intersphinx.
Add `external_projects_current_project` in https://github.com/ROCm/ROCR-Runtime/pull/209.
> fix(projects.yaml): add rocr-runtime

- src/rocm_docs/projects.py
- src/rocm_docs/rocm_docs_theme/sections/header.html
- src/rocm_docs/rocm_docs_theme/theme.conf
- src/rocm_docs/theme.py
to address https://github.com/ROCm/rocm-docs-core/issues/757
> fix: Get header version from URL instead of theme.conf

- src/rocm_docs/rocm_docs_theme/static/custom.css
The list with multiple lines are not readable in dark mode.
Before:
After:
> Fix the line color at dark mode

- src/rocm_docs/rocm_docs_theme/flavors/rocm/header.jinja
since install docs are now public
> fix(header.jinja): Make GitHub repo url for install docs point to install docs instead of ROCm home

- src/rocm_docs/data/projects.yaml
I could clean up the lines, but I saw a couple other repos also point "development_branch: develop".  Let me know if you'd rather we just make them like the other projects (one-liners).
This PR should resolve the intersphinx on develop:
> fix(project.yaml): rocDecode and rocAL default to develop branch now

- docs/demo/doxygen/Doxyfile
- src/rocm_docs/doxygen.py
Removes unused or outdated configs throwing warnings for the rocm-docs-core documentation (https://rocm.docs.amd.com/projects/rocm-docs-core/en/latest/)
> Fix doc warnings for rocm-docs-core

- tests/sites/doxygen/legacy/conf.py
Add more vars and explanations to the legacy Sphinx config used in tests
To serve as reference for using the rocm-docs-core package
> test: Add more vars and explanations to legacy Sphinx config

- src/rocm_docs/data/projects.yaml
Use docs/develop instead of develop for default doc development branch for HIP
> fix(projects.yaml): Update doc dev branch for HIP to docs/develop

- .spellcheck.yaml
Small fix to the spellcheck, so that it doesn't mark known words that are written with a possessive s as spelling error
> ci(spellcheck): Don't fail on known words with a possessive s

- .github/workflows/linting.yml
GitHub actions are getting the following warning: 
"The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/"
> Update checkout action to v4 in linting.xml

- src/rocm_docs/rocm_docs_theme/flavors/rocm-blogs/header.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm/header.jinja
Closes https://github.com/ROCm/rocm-docs-core/issues/964
to avoid redirects from eg: http://github.com/rocm/rocm to https://github.com/rocm/rocm
> fix(header.jinja): Replace http with https in repo URL

- src/rocm_docs/rocm_docs_theme/flavors/generic/footer.jinja
- src/rocm_docs/rocm_docs_theme/flavors/generic/header.jinja
- src/rocm_docs/rocm_docs_theme/flavors/generic/left-side-menu.jinja
- src/rocm_docs/rocm_docs_theme/theme.conf
- src/rocm_docs/theme.py
This PR adds an additional "generic" theme flavor that is completely customizable via `conf.py`. The motivation for this new flavor is for non-ROCm specific sites (e.g. dcgpu.docs.amd.com).
> Add generic theme flavor

- src/rocm_docs/theme.py
This PR updates `theme.py` to add `generic` to the `supported_flavors` list
> fix: add "generic" to supported_flavors list

- src/rocm_docs/data/projects.yaml
>Documentation for Tensile is now available. Tensile is a library that creates benchmark-driven backend implementations for GEMMs, serving primarily as a backend component of rocBLAS. See the [Tensile documentation](https://rocm.docs.amd.com/projects/Tensile/en/docs-6.3.0/src/index.html).
> feat(projects.yaml): Add tensile to intersphinx mapping

- src/rocm_docs/data/_doxygen/extra_stylesheet.css
- src/rocm_docs/rocm_docs_theme/static/custom.css
- src/rocm_docs/rocm_docs_theme/static/rocm_footer.css
- src/rocm_docs/rocm_docs_theme/static/rocm_header.css
The new flyout feature introduced by readthedocs has z-index set to 3000. I'm scaling down our z-index setting to prevent the flyout being covered by other elements.
> fix: scale down z-axis of multiple elements to prevent covering flyout

- .github/workflows/linting.yml
- .github/workflows/yaml_merger.py
- .spellcheck.local.yaml
- .spellcheck.yaml
This PR contains the following update:
- Added config to spell-check C++ files in `.spellcheck.yaml`
- Added a file `.spellcheck.local.yaml` that can be used as a reference for other projects when they want to specify additional sources
- Added a python script `docs/yaml_merger.py` to merge any project's `.spellcheck.local.yaml` with the main `.spellcheck.yaml` in this repository. The script simply checks the nodes `name` and `source` and ensures they match before merging the additional sources (node depth must match too). Anything else is ignored.
> Improve spellcheck script to allow for projects to specify additional sources

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .github/workflows/version-bump.yml
v3 actions has been deprecated, updating workflow actions to v4.
For upload-artifacts, v4.4 excludes hidden files by default, I'm not sure .devcontainer needs to be uploaded so I'm updating the version to v4.3.6
> ci: update upload-artifacts/download-artifacts/checkout actions

- src/rocm_docs/rocm_docs_theme/flavors/rocm-ds/header.jinja
rocm-ds portal intends to use a different version to rocm portal, delete branch == "latest" case to prevent it from using rocm's latest version.
Added definition to verison_list()
> fix: add verison_list() function definition to rocm-ds flavor

- .github/workflows/release.yml
Old 1.8.5 version is not compatible with metadata v2.4 as addressed: https://github.com/pypa/gh-action-pypi-publish/issues/351
This causes the following error: 
Update pypa/gh-action-pypi-publish to the newest version to fix it.
> ci: update pypi publish action to support metadata v2.4

- src/rocm_docs/rocm_docs_theme/flavors/rocm-ds/header.jinja
These items were previously removed due to repo's visibility. Now they are public and time to put them back!
> fix: repo publication approved; revert back menu items

- src/rocm_docs/util.py
The PR modifies the code that extracts repo's url based on the local clone. The current implementation considers two cases:
- git@github.com:ROCm/ROCm.git (SSH format)
- https://github.com/ROCm/ROCm.git (HTTP format)
However, in SSH format, the ".git" suffix is optional. It is valid for users to clone using git@github.com:ROCm/ROCm and the match will fail. In addition, due to EMU repos, the user will have a secondary SSH key causing the prefix not following the "git@xxx.xxx" format. 
Modifying the existing pattern to make .git suffix optional and adding a new pattern for non github.com SSH key.
> fix: add edge cases to SSH pattern matching

- .github/workflows/linting.yml
`raw.github.com` is deprecated in `linting.yml`, change to use `raw.githubusercontent.com` as in other files.
> ci: Update GitHub raw domain in linting.yml
