ROCm/rocm-docs-core

- src/rocm_docs/__init__.py
- src/rocm_docs/util.py
Reference: https://github.com/saadrahim/ROCm/pull/4/files
Update paths to match Pitchfork Layout for doxygen and table of contents yaml file
ie;
- root
-- conf.py
- docs
-- _toc.yml.in
- doxygen
> Update paths to match Pitchfork Layout

- src/rocm_docs/__init__.py
- src/rocm_docs/util.py
toc moved from /docs/ to /docs/sphinx
> Moved toc to sphinx folder

- src/rocm_docs/data/_static/rocm_footer.css
- src/rocm_docs/data/_templates/sections/footer.html
adds a button called "cookie settings" and some styling
> Footer cookie button

- src/rocm_docs/data/_static/rocm_footer.css
- src/rocm_docs/data/_templates/sections/footer.html
Change cookie settings from button to anchor
Remove button CSS to match the rest of the footer
> Change cookie settings from button to anchor

- src/rocm_docs/data/_static/custom.css
Restyles cookie settings to match other links in footer
> Cookie settings CSS

- src/rocm_docs/data/_templates/components/left-side-menu.html
Point to https://rocmdocs.amd.com/projects/alpha/en/develop/
> Update main docs link

- pyproject.toml
> Update to version 0.0.2

- src/rocm_docs/__init__.py
Ref: https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#the-numref-role
> Enable figure numbers by default

- src/rocm_docs/util.py
The edit button url rewriting only handled `git@<owner>:<repo>.git` urls (read the docs clones in this style), but when working locally one might clone using http(s) in which case the git remote is in the form `http(s)://<domain>/<owner>/<repo>.git`. Handle these in addition to ssh style.
> Fix edit button for http remotes

- src/rocm_docs/rocm_docs_theme/sections/header.html
- src/rocm_docs/rocm_docs_theme/static/custom.css
- src/rocm_docs/rocm_docs_theme/static/rocm_footer.css
Increase font size
Change link colors in light/dark mode themes
Fix header GitHub link to point to ROCm docs
> Accessibility Changes

- requirements.txt
duplicates PRs made by dependabot, modified commit message to conform to commitizen
closes #74, #81, #82, #84, #85, #86
> Build(requirements.txt): update requirements

- .wordlist.txt
for ROCm documentation
https://github.com/RadeonOpenCompute/ROCm/pull/2078
> Add new words to wordlist

- .wordlist.txt
Needed for https://github.com/RadeonOpenCompute/ROCm/pull/2067
> ci(spelling): minor word list changes

- .wordlist.txt
Is blocking [ROCm#2103](https://github.com/RadeonOpenCompute/ROCm/pull/2103)
> Add "allocators" to word list

- requirements.txt
- src/rocm_docs/core.py
- src/rocm_docs/rocm_docs_theme/components/article-info.html
`.readthedocs.yaml` config `format` will run sphinx for each requested format (htmlzip, pdf, etc.)
> Check for existing article info before inserting

- src/rocm_docs/rocm_docs_theme/static/custom.css
> cookie settings button styling

- .wordlist.txt
I also started adding why certain dictionary entries were added, and when they're acronyms, what their expansion is.
> Dictionary entries for MI100 & MI200 guides

- docs/conf.py
- src/rocm_docs/core.py
- Use app.outdir instead of extra config setting
- Simplify the logic using the Sphinx Project API
- Use gitpython instead of raw git to get modification dates
- fixes an issue if build is not started from the docs folder
- Fix typing errors and format with black
> Various fixes around article info

- README.md
- docs/index.md
Example of documentation workflow scenario: fixing a typo and updating instructions
> docs: fix typo example

- .readthedocs.yaml
- README.md
- docs/index.md
Rebased to sync with main
Example of documentation workflow scenario: fixing a typo and updating instructions
> docs: update instructions and fix typo example

- src/rocm_docs/__init__.py
- src/rocm_docs/rocm_docs_theme/static/custom.css
remove disable_main_doc_link method (no longer used)
make cookie button text color match rest of header
> Small Fixes

- src/rocm_docs/projects.py
- src/rocm_docs/rocm_docs_theme/sections/header.html
- src/rocm_docs/rocm_docs_theme/static/renameVersionLinks.js
- src/rocm_docs/rocm_docs_theme/static/rocm_footer.css
- src/rocm_docs/theme.py
- src/rocm_docs/util.py
- Navbar links open in new tab
- GitHub navbar links go to project page
- Sidebar CSS fix
- Renaming RTD links fix
> Assorted fixes

- .wordlist.txt
Relates to [this](https://github.com/RadeonOpenCompute/ROCm/pull/2149) PR.
> Vocabulary entries used in RDNA2 virt guide

- src/rocm_docs/rocm_docs_theme/static/renameVersionLinks.js
Regex needs global flag to be used with replaceAll
> Fix type mismatch in versioning script

- src/rocm_docs/core.py
> Round read times

- src/rocm_docs/rocm_docs_theme/static/custom.css
closes https://github.com/RadeonOpenCompute/rocm-docs-core/issues/219
> fix(custom.css): force navbar text to left align and format main doc link

- src/rocm_docs/rocm_docs_theme/static/rdcMisc.js
- src/rocm_docs/rocm_docs_theme/static/theme_mode_captions.js
- src/rocm_docs/theme.py
toggle light/dark mode caption when changing themes
- change caption to display "auto" for auto, "light" for light mode, "dark" for dark mode when switching between theme modes
- initial caption remains "light/dark" to indicate that it is a theme mode switcher
> Update Captions for Theme modes

- docs/.sphinx/_toc.yml.in
- src/rocm_docs/rocm_docs_theme/sections/header.html
Include the version number in the top level header if the branch contains it. Other branch names remain the same
e.g.:
docs/5.5.1 > ROCm TM Platform 5.5.1
develop > ROCm TM Platform develop
main > ROCm TM Platform main
> Add branch name to top level header

- src/rocm_docs/projects.py
missing a char for the future release logic
> fix(projects.py): use formatted string for doc latest url

- src/rocm_docs/projects.py
- src/rocm_docs/rocm_docs_theme/sections/header.html
Use the default flyout position for consistency
Do not put an announcement on latest version
> Appearance changes for consistency

- src/rocm_docs/data/projects.yaml
RE: https://github.com/GPUOpen-ProfessionalCompute-Libraries/rpp/pull/173
> fix(projects.yaml): add rpp to projects.yaml

- pyproject.toml
- src/rocm_docs/__init__.py
- src/rocm_docs/projects.py
- Use the same codepath for announcements as intersphinx mappings in projects.py
- Misc cleanup in projects.py
- enable and fix unused argument linting
> Projects.py cleanup

- src/rocm_docs/data/projects.yaml
add hip python to projects yaml
set development branch to develop for rpp
> ci(projects.yaml): update projects yaml

- .wordlist.txt
- docs/user_guide/linting.md
- docs/user_guide/spellcheck.md
user guidelines for linting and spell checks
closes https://github.com/RadeonOpenCompute/ROCm/issues/2346
closes https://github.com/RadeonOpenCompute/rocm-docs-core/issues/327
> Add references to user guide for spell check and linting

- src/rocm_docs/data/projects.yaml
also alphabetize projects list
> fix(projects.yaml): add hipsparselt to projects yaml

- requirements.txt
- src/rocm_docs/core.py
- src/rocm_docs/doxygen.py
- src/rocm_docs/projects.py
- src/rocm_docs/theme.py
Mypy had some new errors related to untyped imports, those are fixed in this commit.
> build(deps): Upgrade dependencies

- .github/workflows/linting.yml
RST linting is giving false negatives
> build(linting.yml): Remove RST linting

- src/rocm_docs/projects.py
- src/rocm_docs/rocm_docs_theme/theme.conf
> feat: Update latest ROCm version in projects.py and theme.conf

- README.md
- docs/.sphinx/_toc.yml.in
- docs/developer_guide/developer_guide.md
- docs/index.md
- docs/user_guide/user_guide.md
Also update README with link to tests (both current and legacy conf.py) as explanation for usage
> Update User and Developer Guides

- .spellcheck.yaml
Reverts RadeonOpenCompute/rocm-docs-core#488
> Revert "ci(.spellcheck.yaml): Include RST for spellcheck"

- .spellcheck.yaml
Fix small mistake in regular expression.
> Fix ReST code blocks ignore regular expression

- .spellcheck.yaml
> ci(.spellcheck.yaml): Fix ReST code blocks ignore regular expression

- .spellcheck.yaml
* ```.. _reference:```
* ```.. math::```
> ci(.spellcheck.yaml): Update .spellcheck.yaml ReST math and reference

- src/rocm_docs/rocm_docs_theme/flavors/list/left-side-menu.jinja
relates to https://github.com/RadeonOpenCompute/rocm-docs-core/issues/534
> feat: Add new flavor - list theme

- src/rocm_docs/data/projects.yaml
Closes https://github.com/RadeonOpenCompute/rocm-docs-core/issues/535
> feat(projects.yaml): Add linux install guide to projects.yaml

- .spellcheck.yaml
- .wordlist.txt
> Add new RST directives to ignore

- .github/dependabot.yml
Add labels, reviewers, and reduce interval to daily
> build(dependabot.yml): Change dependabot config

- src/rocm_docs/projects.py
- src/rocm_docs/rocm_docs_theme/theme.conf
- src/rocm_docs/theme.py
> Latest version update for ROCm header

- docs/conf.py
- src/rocm_docs/rocm_docs_theme/flavors/rocm-blogs/footer.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm-blogs/header.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm-blogs/left-side-menu.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm/footer.jinja
- src/rocm_docs/rocm_docs_theme/sections/footer.html
- src/rocm_docs/theme.py
New flavor:
- no license in footer
- no version in header
- left side menu main doc link directs to rocm docs home
Modifies footer.html template to make license optional
> feat: Add ROCm blogs flavor

- src/rocm_docs/rocm_docs_theme/flavors/rocm-blogs/header.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm/header.jinja
- src/rocm_docs/rocm_docs_theme/sections/header.html
closes https://github.com/ROCm/rocm-docs-core/issues/617
> Blog flavor edits

- src/rocm_docs/rocm_docs_theme/flavors/rocm/left-side-menu.jinja
> fix(left-side-menu.jinja): Fix main doc link for rocm flavor

- .wordlist.txt
for https://github.com/ROCm/ROCm/pull/2970
> ci(.wordlist.txt): Add unallocated to wordlist

- .wordlist.txt
- docs/user_guide/doxygen_integration.md
Adds practical steps involved in doxygen integration with sphinx
> docs: Add more information about doxygen integration

- .spellcheck.yaml
- Handle one line doxygen
- Update figure handle at rst files
- Ignore docs/doxygen/mainpage.md
> Update spellcheck yml

- .github/workflows/linting.yml
- README.md
- docs/developer_guide/dependabot.md
- docs/developer_guide/just.md
- docs/user_guide/doxygen_integration.md
- docs/user_guide/linking.md
- pyproject.toml
- requirements.txt
- src/rocm_docs/data/projects.schema.json
- src/rocm_docs/projects.py
- src/rocm_docs/rocm_docs_theme/flavors/rocm-blogs/header.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm/header.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm/meta.jinja
- src/rocm_docs/rocm_docs_theme/sections/meta.html
- src/rocm_docs/theme.py
Closes https://github.com/ROCm/rocm-docs-core/issues/768
> Google Site Verification

- docs/conf.py
- src/rocm_docs/data/projects.yaml
- tests/sites/doxygen/extension/conf.py
- tests/sites/doxygen/legacy/conf.py
- tests/sites/pass/minimal_legacy/conf.py
Adds omniperf and omnitrace
Also updates rocm-docs-core site tests
> Add new doc projects and update rocm-docs-core docs

- docs/user_guide/linking.md
- src/rocm_docs/data/projects.yaml
- src/rocm_docs/projects.py
Closes https://github.com/ROCm/rocm-docs-core/issues/869
The next minor version needs to be published to begin using new links
User Guide: https://advanced-micro-devices-demo--870.com.readthedocs.build/projects/rocm-docs-core/en/870/user_guide/linking.html or docs/user_guide/linking.md
> Add Links for GitHub and files

- .wordlist.txt
- docs/user_guide/spellcheck.md
> docs: Update Spellcheck docs

- .spellcheck.yaml
for checking spelling on ROCm https://github.com/ROCm/ROCm/tree/develop/tools/autotag/templates
> ci(.spellcheck.yaml): Check templates for spelling

- src/rocm_docs/projects.py
To avoid wrong banner for docs/develop branch on HIP
https://rocm.docs.amd.com/projects/HIP/en/docs-develop/
> fix(projects.py): Update pattern matching for old release announcement

- src/rocm_docs/rocm_docs_theme/static/custom.css
- src/rocm_docs/theme.py
Changes phrasing for old versions
Makes link a lighter shade of blue
> Improve readability of the banner

- src/rocm_docs/data/projects.yaml
Closes https://github.com/ROCm/rocm-docs-core/issues/937
> fix(projects.yaml): Remove non-doc cross refs

- src/rocm_docs/theme.py
> style(theme.py): Apply black formatter

- src/rocm_docs/data/projects.yaml
- src/rocm_docs/rocm_docs_theme/flavors/instinct/header.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm-blogs/header.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm-ds/footer.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm-ds/header.jinja
- src/rocm_docs/rocm_docs_theme/flavors/rocm-ds/left-side-menu.jinja
- src/rocm_docs/theme.py
Add a new flavor for ROCm Data Science portal.
This PR also unifies some inconsistency in "ROCm Docs" header from blogs and instinct flavors.
> feat: add rocm-ds flavor

- src/rocm_docs/rocm_docs_theme/flavors/rocm-ds/header.jinja
A hardcoded solution for EA due to limited time. Will replace with a more robust solution later.
> Header version update for ROCm-DS theme

- LICENSE.txt
Change `src/rocm_docs/data/_images` to `src/rocm_docs/rocm_docs_theme/static/images`
> fix: Update LICENSE.txt

- src/rocm_docs/data/projects.yaml
Fix: Radeon page projects.yaml update
projects.yaml can handle now sparse versions.
> Fix: Radeon page projects.yaml update
